from jupyter_deploy import verify_utils
from jupyter_deploy.engine.engine_config import EngineConfigHandler
from jupyter_deploy.engine.enum import EngineType
from jupyter_deploy.engine.supervised_execution import CompletionContext, DisplayManager
from jupyter_deploy.engine.terraform import tf_config
from jupyter_deploy.engine.vardefs import TemplateVariableDefinition
from jupyter_deploy.enum import StoreType
from jupyter_deploy.exceptions import InvalidPresetError
from jupyter_deploy.handlers.base_project_handler import BaseProjectHandler, write_store_config
from jupyter_deploy.provider.store.store_manager import StoreInfo
from jupyter_deploy.provider.store.store_manager_factory import StoreManagerFactory


class ConfigHandler(BaseProjectHandler):
    _handler: EngineConfigHandler

    def __init__(self, display_manager: DisplayManager, output_filename: str | None = None) -> None:
        """Base class to manage the configuration of a jupyter-deploy project."""
        super().__init__(display_manager=display_manager)
        self.preset_name: str | None = None

        if self.engine == EngineType.TERRAFORM:
            self._handler = tf_config.TerraformConfigHandler(
                project_path=self.project_path,
                project_manifest=self.project_manifest,
                command_history_handler=self.command_history_handler,
                output_filename=output_filename,
                display_manager=display_manager,
            )
        else:
            raise NotImplementedError(f"ConfigHandler implementation not found for engine: {self.engine}")

    def has_recorded_variables(self) -> bool:
        """Return True if the file generated by jd config to record variable values exists."""
        return self._handler.has_recorded_variables()

    def verify_preset_exists(self, preset_name: str) -> bool:
        """Return True if the requested preset is defined by this template."""
        return self._handler.verify_preset_exists(preset_name)

    def list_presets(self) -> list[str]:
        """Return the list of default presets that this template supports."""
        return self._handler.list_presets()

    def validate_preset(self, preset_name: str) -> None:
        """Validate that the preset exists, raise InvalidPresetError if not.

        Raises:
            InvalidPresetError: If the preset is not valid for this template.
        """
        if not self.verify_preset_exists(preset_name):
            valid_presets = self.list_presets()
            raise InvalidPresetError(preset_name, valid_presets)

    def set_preset(self, preset_name: str | None) -> None:
        """Set the preset name to use for configuration."""
        self.preset_name = preset_name

    def verify_requirements(self) -> None:
        """Verify that all required tools are installed.

        Raises:
            ToolRequiredError: If a required tool is not installed or has an incorrect version.
        """
        requirements = self.project_manifest.get_requirements()
        verify_utils.verify_tools_installation(requirements)

    def has_used_preset(self, expected_preset_name: str | None) -> bool:
        """Return True if the handler has used the preset.

        Always return True if expected_preset argument is None.
        This method returns False when it detected recorded variables values that the users
        decided not to reset.
        """
        return expected_preset_name is None or expected_preset_name == self.preset_name

    def reset_recorded_variables(self) -> bool:
        """Delete the file in the project dir where the previous inputs were recorded.

        Returns:
            bool: True if files were deleted, False otherwise
        """
        return self._handler.reset_recorded_variables()

    def reset_recorded_secrets(self) -> bool:
        """Delete the file in the project dir where the secrets were recorded.

        Returns:
            bool: True if files were deleted, False otherwise
        """
        return self._handler.reset_recorded_secrets()

    def ensure_store(
        self,
        store_type: StoreType | None = None,
        store_id: str | None = None,
    ) -> StoreInfo | None:
        """Ensure the remote project store exists, creating it if necessary.

        Resolves store type and ID from CLI args > .jd/store.yaml > manifest.
        Persists resolved values to .jd/store.yaml so subsequent runs skip discovery.

        When store_id is explicitly set, verifies the store exists with find_store()
        and raises ProjectStoreNotFoundError if not found.

        Returns:
            StoreInfo if the store was ensured, None if project store is not configured.

        Raises:
            ProjectStoreNotFoundError: If store_id is set but the store does not exist.
        """
        # Resolve store type: CLI > config
        resolved_store_type = store_type if store_type is not None else self.get_store_type_from_config_or_manifest()

        if not resolved_store_type:
            self.display_manager.warning("No project store type configured. Skipping store setup.")
            return None

        # Resolve store id: CLI > config
        resolved_store_id = store_id if store_id else self.get_store_id_from_config()

        # When --store-id is explicitly passed, verify the bucket exists rather than creating one
        if resolved_store_id is not None:
            store_manager = StoreManagerFactory.get_manager(store_type=resolved_store_type, store_id=resolved_store_id)
            store_info = store_manager.find_store()
            write_store_config(self.project_path, store_type=resolved_store_type, store_id=resolved_store_id)
            return store_info

        store_manager = StoreManagerFactory.get_manager(store_type=resolved_store_type, store_id=resolved_store_id)
        store_info = store_manager.ensure_store(self.display_manager)

        # Persist to .jd/store.yaml so subsequent runs skip discovery
        write_store_config(self.project_path, store_type=resolved_store_type, store_id=store_info.store_id)

        return store_info

    def configure(
        self, variable_overrides: dict[str, TemplateVariableDefinition] | None = None
    ) -> CompletionContext | None:
        """Set inputs of the project, calls the engine, return CompletionContext."""
        return self._handler.configure(preset_name=self.preset_name, variable_overrides=variable_overrides)

    def record(self, record_vars: bool = False, record_secrets: bool = False) -> None:
        """Save the values of the variables to disk in the project dir."""
        self._handler.record(record_vars=record_vars, record_secrets=record_secrets)
