STORE_BUCKET_NAME_PREFIX = "jupyter-deploy-projects"
STORE_DDB_TABLE_NAME = "jupyter-deploy-projects"
STORE_TAG_SOURCE_KEY = "Source"
STORE_TAG_SOURCE_VALUE = "jupyter-deploy-cli"
STORE_TAG_VERSION_KEY = "Version"
